INSERT INTO GENERATOR (GEN_NAME) VALUES ('CUSTOMER_GEN');
INSERT INTO GENERATOR (GEN_NAME) VALUES ('ROLE_GEN');
INSERT INTO GENERATOR (GEN_NAME) VALUES ('CAR_GEN');
INSERT INTO GENERATOR (GEN_NAME) VALUES ('TRANSACTION_TYPE_GEN');
INSERT INTO GENERATOR (GEN_NAME) VALUES ('TRANSACTION_GEN');

INSERT INTO CUSTOMER (CUSTOMER_KEY, CUSTOMER_NAME, FIRST_NAME, LAST_NAME, EMAIL, BIRTHDATE, ENABLED, PASSWORD)
	VALUES ((SELECT MAX(GEN_VALUE) FROM GENERATOR WHERE GEN_NAME = 'CUSTOMER_GEN'), 'admin', 'Maksim', 'Drahun', 'admin@carmanage.net', '1991-02-04', true, 'fcc67c9419ac441040f62374dfb1d4ca455c9b4cd0a1f180efb48b4dd607f44019ab34a51c38af1e');
UPDATE GENERATOR SET GEN_VALUE = GEN_VALUE + 1 WHERE GEN_NAME = 'CUSTOMER_GEN';
INSERT INTO CUSTOMER (CUSTOMER_KEY, CUSTOMER_NAME, FIRST_NAME, LAST_NAME, EMAIL, BIRTHDATE, ENABLED, PASSWORD)
	VALUES ((SELECT MAX(GEN_VALUE) FROM GENERATOR WHERE GEN_NAME = 'CUSTOMER_GEN'), 'guest', 'guest', '', 'guest@carmanage.net', null, true, 'fcc67c9419ac441040f62374dfb1d4ca455c9b4cd0a1f180efb48b4dd607f44019ab34a51c38af1e');
UPDATE GENERATOR SET GEN_VALUE = GEN_VALUE + 1 WHERE GEN_NAME = 'CUSTOMER_GEN';
INSERT INTO CUSTOMER (CUSTOMER_KEY, CUSTOMER_NAME, FIRST_NAME, LAST_NAME, EMAIL, BIRTHDATE, ENABLED, PASSWORD)
	VALUES ((SELECT MAX(GEN_VALUE) FROM GENERATOR WHERE GEN_NAME = 'CUSTOMER_GEN'), 'makseemka', 'Maksim', 'Drahun', 'max@carmanage.net', '1991-02-04', true, 'fcc67c9419ac441040f62374dfb1d4ca455c9b4cd0a1f180efb48b4dd607f44019ab34a51c38af1e');
UPDATE GENERATOR SET GEN_VALUE = GEN_VALUE + 1 WHERE GEN_NAME = 'CUSTOMER_GEN';
INSERT INTO CUSTOMER (CUSTOMER_KEY, CUSTOMER_NAME, FIRST_NAME, LAST_NAME, EMAIL, BIRTHDATE, ENABLED, PASSWORD)
	VALUES ((SELECT MAX(GEN_VALUE) FROM GENERATOR WHERE GEN_NAME = 'CUSTOMER_GEN'), 'drahunl', 'Leonid', 'Drahun', 'max@carmanage.net', '1964-11-11', true, 'fcc67c9419ac441040f62374dfb1d4ca455c9b4cd0a1f180efb48b4dd607f44019ab34a51c38af1e');
UPDATE GENERATOR SET GEN_VALUE = GEN_VALUE + 1 WHERE GEN_NAME = 'CUSTOMER_GEN';
INSERT INTO CUSTOMER (CUSTOMER_KEY, CUSTOMER_NAME, FIRST_NAME, LAST_NAME, EMAIL, BIRTHDATE, ENABLED, PASSWORD)
	VALUES ((SELECT MAX(GEN_VALUE) FROM GENERATOR WHERE GEN_NAME = 'CUSTOMER_GEN'), 'dodzv', 'Vitaly', 'Dodz', 'max@carmanage.net', '1991-02-04', true, 'fcc67c9419ac441040f62374dfb1d4ca455c9b4cd0a1f180efb48b4dd607f44019ab34a51c38af1e');
UPDATE GENERATOR SET GEN_VALUE = GEN_VALUE + 1 WHERE GEN_NAME = 'CUSTOMER_GEN';

INSERT INTO ROLE (ROLE_KEY, ROLE_NAME)
	VALUES ((SELECT MAX(GEN_VALUE) FROM GENERATOR WHERE GEN_NAME = 'ROLE_GEN'), 'ADMIN');
UPDATE GENERATOR SET GEN_VALUE = GEN_VALUE + 1 WHERE GEN_NAME = 'ROLE_GEN';
INSERT INTO ROLE (ROLE_KEY, ROLE_NAME)
	VALUES ((SELECT MAX(GEN_VALUE) FROM GENERATOR WHERE GEN_NAME = 'ROLE_GEN'), 'CUSTOMER');
UPDATE GENERATOR SET GEN_VALUE = GEN_VALUE + 1 WHERE GEN_NAME = 'ROLE_GEN';
INSERT INTO ROLE (ROLE_KEY, ROLE_NAME)
	VALUES ((SELECT MAX(GEN_VALUE) FROM GENERATOR WHERE GEN_NAME = 'ROLE_GEN'), 'ANONYMOUS');
UPDATE GENERATOR SET GEN_VALUE = GEN_VALUE + 1 WHERE GEN_NAME = 'ROLE_GEN';

INSERT INTO CUSTOMER_ROLE (CUSTOMER_KEY, ROLE_KEY) 
	VALUES (
		(SELECT CUSTOMER_KEY FROM CUSTOMER WHERE CUSTOMER_NAME = 'admin'), 
		(SELECT ROLE_KEY FROM ROLE WHERE ROLE_NAME = 'ADMIN'));
INSERT INTO CUSTOMER_ROLE (CUSTOMER_KEY, ROLE_KEY) 
	VALUES (
		(SELECT CUSTOMER_KEY FROM CUSTOMER WHERE CUSTOMER_NAME = 'admin'), 
		(SELECT ROLE_KEY FROM ROLE WHERE ROLE_NAME = 'CUSTOMER'));
INSERT INTO CUSTOMER_ROLE (CUSTOMER_KEY, ROLE_KEY) 
	VALUES (
		(SELECT CUSTOMER_KEY FROM CUSTOMER WHERE CUSTOMER_NAME = 'admin'), 
		(SELECT ROLE_KEY FROM ROLE WHERE ROLE_NAME = 'ANONYMOUS'));
INSERT INTO CUSTOMER_ROLE (CUSTOMER_KEY, ROLE_KEY) 
	VALUES (
		(SELECT CUSTOMER_KEY FROM CUSTOMER WHERE CUSTOMER_NAME = 'guest'), 
		(SELECT ROLE_KEY FROM ROLE WHERE ROLE_NAME = 'ANONYMOUS'));
INSERT INTO CUSTOMER_ROLE (CUSTOMER_KEY, ROLE_KEY) 
	VALUES (
		(SELECT CUSTOMER_KEY FROM CUSTOMER WHERE CUSTOMER_NAME = 'makseemka'), 
		(SELECT ROLE_KEY FROM ROLE WHERE ROLE_NAME = 'ADMIN'));
INSERT INTO CUSTOMER_ROLE (CUSTOMER_KEY, ROLE_KEY) 
	VALUES (
		(SELECT CUSTOMER_KEY FROM CUSTOMER WHERE CUSTOMER_NAME = 'makseemka'), 
		(SELECT ROLE_KEY FROM ROLE WHERE ROLE_NAME = 'CUSTOMER'));
INSERT INTO CUSTOMER_ROLE (CUSTOMER_KEY, ROLE_KEY) 
	VALUES (
		(SELECT CUSTOMER_KEY FROM CUSTOMER WHERE CUSTOMER_NAME = 'drahunl'), 
		(SELECT ROLE_KEY FROM ROLE WHERE ROLE_NAME = 'CUSTOMER'));
INSERT INTO CUSTOMER_ROLE (CUSTOMER_KEY, ROLE_KEY) 
	VALUES (
		(SELECT CUSTOMER_KEY FROM CUSTOMER WHERE CUSTOMER_NAME = 'dodzv'), 
		(SELECT ROLE_KEY FROM ROLE WHERE ROLE_NAME = 'CUSTOMER'));
		
INSERT INTO CUSTOMER_PAYER (CUSTOMER_KEY, PAYER_KEY) 
	VALUES (
		(SELECT CUSTOMER_KEY FROM CUSTOMER WHERE CUSTOMER_NAME = 'makseemka'), 
		(SELECT CUSTOMER_KEY FROM CUSTOMER WHERE CUSTOMER_NAME = 'drahunl'));
INSERT INTO CUSTOMER_PAYER (CUSTOMER_KEY, PAYER_KEY) 
	VALUES (
		(SELECT CUSTOMER_KEY FROM CUSTOMER WHERE CUSTOMER_NAME = 'makseemka'), 
		(SELECT CUSTOMER_KEY FROM CUSTOMER WHERE CUSTOMER_NAME = 'dodzv'));

INSERT INTO TRANSACTION_TYPE (TRANSACTION_TYPE_KEY, NAME)
	VALUES ((SELECT MAX(GEN_VALUE) FROM GENERATOR WHERE GEN_NAME = 'TRANSACTION_TYPE_GEN'), 'Fuel');
UPDATE GENERATOR SET GEN_VALUE = GEN_VALUE + 1 WHERE GEN_NAME = 'TRANSACTION_TYPE_GEN';
INSERT INTO TRANSACTION_TYPE (TRANSACTION_TYPE_KEY, NAME)
	VALUES ((SELECT MAX(GEN_VALUE) FROM GENERATOR WHERE GEN_NAME = 'TRANSACTION_TYPE_GEN'), 'LoanPayment');
UPDATE GENERATOR SET GEN_VALUE = GEN_VALUE + 1 WHERE GEN_NAME = 'TRANSACTION_TYPE_GEN';

INSERT INTO CAR (CAR_KEY, BRAND, MODEL, PURCHASE_DATE, CUSTOMER_KEY)
	VALUES ((SELECT MAX(GEN_VALUE) FROM GENERATOR WHERE GEN_NAME = 'CAR_GEN'), 'Mersedes-Benz', 'C180', '2014-11-07', (SELECT CUSTOMER_KEY FROM CUSTOMER WHERE CUSTOMER_NAME = 'makseemka'));
UPDATE GENERATOR SET GEN_VALUE = GEN_VALUE + 1 WHERE GEN_NAME = 'CAR_GEN';

INSERT INTO CUSTOMER_SETTING (CUSTOMER_KEY, NAME, VALUE)
	VALUES ((SELECT CUSTOMER_KEY FROM CUSTOMER WHERE CUSTOMER_NAME = 'makseemka'), 'PREFERRED_PAYMENT_CURRENCY', 'BYN');
INSERT INTO CUSTOMER_SETTING (CUSTOMER_KEY, NAME, VALUE)
	VALUES ((SELECT CUSTOMER_KEY FROM CUSTOMER WHERE CUSTOMER_NAME = 'makseemka'), 'PREFERRED_PAYMENT_TYPE', 'Fuel');
INSERT INTO CUSTOMER_SETTING (CUSTOMER_KEY, NAME, VALUE)
	VALUES ((SELECT CUSTOMER_KEY FROM CUSTOMER WHERE CUSTOMER_NAME = 'makseemka'), 'PREFERRED_FUEL_QUANTITY', '30');
INSERT INTO CUSTOMER_SETTING (CUSTOMER_KEY, NAME, VALUE)
	VALUES ((SELECT CUSTOMER_KEY FROM CUSTOMER WHERE CUSTOMER_NAME = 'makseemka'), 'PREFERRED_FUEL_TYPE', 'АИ92');
INSERT INTO CUSTOMER_SETTING (CUSTOMER_KEY, NAME, VALUE)
	VALUES ((SELECT CUSTOMER_KEY FROM CUSTOMER WHERE CUSTOMER_NAME = 'makseemka'), 'LAST_FUEL_COST', '1.11');
